source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

inhibit_all_warnings!

project 'SimplePopupDemo'

target 'SimplePopupDemo' do
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'
  pod "SimpleKeychain"
  pod 'Alamofire'
  
end
